name: Electron Forge CI

on: [push]

jobs:
  test:
    name: Node - ${{ matrix.node_version }} OS - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node JS Version
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Yarn install, Electron Forge make
      run: |
        yarn install
        yarn make

    - uses: actions/upload-artifact@master
    - name: Upload Artifact
      with:
        name: ${{ matrix.node_version }}-OS-${{ matrix.os }}
        path: out/make
